#!/bin/bash
trap "exit" INT

printf "Starting the tests with: 8, 16, 32, 64 and 128threads."

printf "\n\n8 threads\n"

rm threads.txt
echo "8" >> threads.txt
./helper

mv res.txt 8th.txt

printf "\n\n16 threads\n"

rm threads.txt
echo "16" >> threads.txt
./helper

mv res.txt 16th.txt

printf "\n\n32 threads\n"

rm threads.txt
echo "32" >> threads.txt
./helper

mv res.txt 32th.txt

printf "\n\n64 threads\n"

rm threads.txt
echo "64" >> threads.txt
./helper

mv res.txt 64th.txt

printf "\n\n128 threads\n"

rm threads.txt
echo "128" >> threads.txt
./helper

mv res.txt 128th.txt
