#!/bin/bash
trap "exit" INT

printf "Starting the tests with: 4, 8, 16, 32, 64, 128, 1024, 2048 threads."

printf "\n\n4 threads\n"

rm threads.txt
echo "4" >> threads.txt
./helper

mv res.txt 4th.txt

printf "\n\n8 threads\n"

rm threads.txt
echo "8" >> threads.txt
./helper

mv res.txt 8th.txt

printf "\n\n16 threads\n"

rm threads.txt
echo "16" >> threads.txt
./helper

mv res.txt 16th.txt

printf "\n\n32 threads\n"

rm threads.txt
echo "32" >> threads.txt
./helper

mv res.txt 32th.txt

printf "\n\n64 threads\n"

rm threads.txt
echo "64" >> threads.txt
./helper

mv res.txt 64th.txt

printf "\n\n128 threads\n"

rm threads.txt
echo "128" >> threads.txt
./helper

mv res.txt 128th.txt

printf "\n\n256 threads\n"

rm threads.txt
echo "256" >> threads.txt
./helper

mv res.txt 256th.txt

printf "\n\n512 threads\n"

rm threads.txt
echo "512" >> threads.txt
./helper

mv res.txt 512th.txt

printf "\n\n1024 threads\n"

rm threads.txt
echo "1024" >> threads.txt
./helper

mv res.txt 1024th.txt

printf "\n\n2048 threads\n"

rm threads.txt
echo "2048" >> threads.txt
./helper

mv res.txt 2048th.txt
